// <auto-generated />
using System;
using Lisbeth.Bot.DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Lisbeth.Bot.DataAccessLayer.Migrations
{
    [DbContext(typeof(LisbethBotDbContext))]
    [Migration("20211024124816_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Lisbeth.Bot.Domain.Entities.Ban", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("AppliedById")
                        .HasColumnType("bigint")
                        .HasColumnName("applied_by_id");

                    b.Property<DateTime?>("AppliedUntil")
                        .IsRequired()
                        .HasColumnType("timestamp")
                        .HasColumnName("applied_until");

                    b.Property<DateTime?>("CreatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<long>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_disabled");

                    b.Property<long>("LiftedById")
                        .HasColumnType("bigint")
                        .HasColumnName("lifted_by_id");

                    b.Property<DateTime?>("LiftedOn")
                        .HasColumnType("timestamp")
                        .HasColumnName("lifted_on");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("reason");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.ToTable("ban");
                });

            modelBuilder.Entity("Lisbeth.Bot.Domain.Entities.EmbedConfig", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Author")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("author");

                    b.Property<string>("AuthorImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("author_image_url");

                    b.Property<DateTime?>("CreatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Fields")
                        .HasColumnType("text")
                        .HasColumnName("fields");

                    b.Property<string>("Footer")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("footer");

                    b.Property<string>("FooterImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("footer_image_url");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_disabled");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("embed_config");
                });

            modelBuilder.Entity("Lisbeth.Bot.Domain.Entities.Guild", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime?>("CreatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<string>("EmbedHexColor")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("embed_hex_color");

                    b.Property<long>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_disabled");

                    b.Property<long?>("ReminderChannelId")
                        .HasColumnType("bigint")
                        .HasColumnName("reminder_channel_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("inviter_id");

                    b.HasKey("Id");

                    b.ToTable("guild");
                });

            modelBuilder.Entity("Lisbeth.Bot.Domain.Entities.GuildServerBooster", b =>
                {
                    b.Property<long>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

                    b.Property<long>("ServerBoosterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

                    b.HasKey("GuildId", "ServerBoosterId");

                    b.HasIndex("ServerBoosterId");

                    b.ToTable("guild_server_booster");
                });

            modelBuilder.Entity("Lisbeth.Bot.Domain.Entities.Mute", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("AppliedById")
                        .HasColumnType("bigint")
                        .HasColumnName("applied_by_id");

                    b.Property<DateTime?>("AppliedUntil")
                        .IsRequired()
                        .HasColumnType("timestamp")
                        .HasColumnName("applied_until");

                    b.Property<DateTime?>("CreatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<long>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_disabled");

                    b.Property<long>("LiftedById")
                        .HasColumnType("bigint")
                        .HasColumnName("lifted_by_id");

                    b.Property<DateTime?>("LiftedOn")
                        .HasColumnType("timestamp")
                        .HasColumnName("lifted_on");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("reason");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.ToTable("mute");
                });

            modelBuilder.Entity("Lisbeth.Bot.Domain.Entities.Prune", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint")
                        .HasColumnName("channel_id");

                    b.Property<int>("Count")
                        .HasColumnType("int")
                        .HasColumnName("count");

                    b.Property<DateTime?>("CreatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<long>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_disabled");

                    b.Property<string>("Messages")
                        .HasColumnType("text")
                        .HasColumnName("messages");

                    b.Property<long>("ModeratorId")
                        .HasColumnType("bigint")
                        .HasColumnName("moderator_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.ToTable("prune");
                });

            modelBuilder.Entity("Lisbeth.Bot.Domain.Entities.RecurringReminder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime?>("CreatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("cron_expression");

                    b.Property<long?>("EmbedConfigId")
                        .HasColumnType("bigint")
                        .HasColumnName("embed_config_id");

                    b.Property<long?>("GuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_disabled");

                    b.Property<string>("Mentions")
                        .HasColumnType("text")
                        .HasColumnName("tags");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Text")
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("EmbedConfigId")
                        .IsUnique();

                    b.HasIndex("GuildId");

                    b.ToTable("recurring_reminder");
                });

            modelBuilder.Entity("Lisbeth.Bot.Domain.Entities.Reminder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime?>("CreatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<long?>("EmbedConfigId")
                        .HasColumnType("bigint")
                        .HasColumnName("embed_config_id");

                    b.Property<long?>("GuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_disabled");

                    b.Property<string>("Mentions")
                        .HasColumnType("text")
                        .HasColumnName("tags");

                    b.Property<DateTime>("SetForDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("set_for_date");

                    b.Property<string>("Text")
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("EmbedConfigId")
                        .IsUnique();

                    b.HasIndex("GuildId");

                    b.ToTable("reminder");
                });

            modelBuilder.Entity("Lisbeth.Bot.Domain.Entities.RoleMenu", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime?>("CreatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<long>("EmbedConfigId")
                        .HasColumnType("bigint")
                        .HasColumnName("embed_config_id");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_disabled");

                    b.Property<long>("MessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("message_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("RoleEmojiMapping")
                        .HasColumnType("text")
                        .HasColumnName("role_emoji_mapping");

                    b.Property<string>("Text")
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("EmbedConfigId")
                        .IsUnique();

                    b.HasIndex("GuildId");

                    b.ToTable("role_menu");
                });

            modelBuilder.Entity("Lisbeth.Bot.Domain.Entities.ServerBooster", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("BoostCount")
                        .HasColumnType("int")
                        .HasColumnName("boost_count");

                    b.Property<DateTime>("BoostingSince")
                        .HasColumnType("timestamp")
                        .HasColumnName("boosting_since");

                    b.Property<DateTime?>("CreatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<long>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_disabled");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

                    b.HasKey("Id");

                    b.ToTable("server_booster");
                });

            modelBuilder.Entity("Lisbeth.Bot.Domain.Entities.Tag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime?>("CreatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<long?>("EmbedConfigId")
                        .HasColumnType("bigint")
                        .HasColumnName("embed_config_id");

                    b.Property<long>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_disabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Text")
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

                    b.HasKey("Id");

                    b.HasIndex("EmbedConfigId")
                        .IsUnique();

                    b.HasIndex("GuildId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("tag");
                });

            modelBuilder.Entity("Lisbeth.Bot.Domain.Entities.Ticket", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("AddedRoleIds")
                        .HasColumnType("text")
                        .HasColumnName("added_roles");

                    b.Property<string>("AddedUserIds")
                        .HasColumnType("text")
                        .HasColumnName("added_users");

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint")
                        .HasColumnName("channel_id");

                    b.Property<long?>("ClosedById")
                        .HasColumnType("bigint")
                        .HasColumnName("closed_by_id");

                    b.Property<DateTime?>("ClosedOn")
                        .HasColumnType("timestamp")
                        .HasColumnName("closed_on");

                    b.Property<DateTime?>("CreatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<long>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

                    b.Property<long>("GuildSpecificId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_specific_id");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_disabled");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean")
                        .HasColumnName("is_private");

                    b.Property<long?>("MessageCloseId")
                        .HasColumnType("bigint")
                        .HasColumnName("message_close_id");

                    b.Property<long>("MessageOpenId")
                        .HasColumnType("bigint")
                        .HasColumnName("message_open_id");

                    b.Property<long?>("MessageReopenId")
                        .HasColumnType("bigint")
                        .HasColumnName("message_reopen_id");

                    b.Property<long?>("ReopenedById")
                        .HasColumnType("bigint")
                        .HasColumnName("reopened_by_id");

                    b.Property<DateTime?>("ReopenedOn")
                        .HasColumnType("timestamp")
                        .HasColumnName("reopened_on");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.ToTable("ticket");
                });

            modelBuilder.Entity("MikyM.Common.Domain.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("AffectedColumns")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("affected_columns");

                    b.Property<DateTime?>("CreatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_disabled");

                    b.Property<string>("NewValues")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("new_values");

                    b.Property<string>("OldValues")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("old_values");

                    b.Property<string>("PrimaryKey")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("primary_key");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("table_name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("audit_log");
                });

            modelBuilder.Entity("Lisbeth.Bot.Domain.Entities.Ban", b =>
                {
                    b.HasOne("Lisbeth.Bot.Domain.Entities.Guild", "Guild")
                        .WithMany("Bans")
                        .HasForeignKey("GuildId")
                        .HasPrincipalKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Lisbeth.Bot.Domain.Entities.Guild", b =>
                {
                    b.OwnsOne("Lisbeth.Bot.Domain.Entities.ModerationConfig", "ModerationConfig", b1 =>
                        {
                            b1.Property<long>("GuildId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasColumnName("guild_id");

                            b1.Property<DateTime?>("CreatedAt")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp")
                                .HasColumnName("created_at");

                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasColumnName("id")
                                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                            b1.Property<bool>("IsDisabled")
                                .HasColumnType("boolean")
                                .HasColumnName("is_disabled");

                            b1.Property<long?>("MemberEventsLogChannelId")
                                .HasColumnType("bigint")
                                .HasColumnName("member_events_log_channel_id");

                            b1.Property<string>("MemberWelcomeMessage")
                                .HasColumnType("text")
                                .HasColumnName("member_welcome_message");

                            b1.Property<string>("MemberWelcomeMessageTitle")
                                .HasMaxLength(256)
                                .HasColumnType("varchar(256)")
                                .HasColumnName("member_welcome_message_title");

                            b1.Property<long?>("MessageDeletedEventsLogChannelId")
                                .HasColumnType("bigint")
                                .HasColumnName("message_deleted_events_log_channel_id");

                            b1.Property<long?>("MessageUpdatedEventsLogChannelId")
                                .HasColumnType("bigint")
                                .HasColumnName("message_updated_events_log_channel_id");

                            b1.Property<long>("MuteRoleId")
                                .HasColumnType("bigint")
                                .HasColumnName("mute_role_id");

                            b1.Property<DateTime?>("UpdatedAt")
                                .IsRequired()
                                .HasColumnType("timestamp")
                                .HasColumnName("updated_at");

                            b1.HasKey("GuildId");

                            b1.ToTable("guild_moderation_config");

                            b1.WithOwner("Guild")
                                .HasForeignKey("GuildId");

                            b1.Navigation("Guild");
                        });

                    b.OwnsOne("Lisbeth.Bot.Domain.Entities.TicketingConfig", "TicketingConfig", b1 =>
                        {
                            b1.Property<long>("GuildId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasColumnName("guild_id");

                            b1.Property<long?>("CleanAfter")
                                .HasColumnType("bigint")
                                .HasColumnName("clean_after");

                            b1.Property<long?>("CloseAfter")
                                .HasColumnType("bigint")
                                .HasColumnName("close_after");

                            b1.Property<long>("ClosedCategoryId")
                                .HasColumnType("bigint")
                                .HasColumnName("closed_category_id");

                            b1.Property<string>("ClosedNamePrefix")
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("closed_name_prefix");

                            b1.Property<DateTime?>("CreatedAt")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp")
                                .HasColumnName("created_at");

                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasColumnName("id")
                                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                            b1.Property<bool>("IsDisabled")
                                .HasColumnType("boolean")
                                .HasColumnName("is_disabled");

                            b1.Property<long>("LastTicketId")
                                .HasColumnType("bigint")
                                .HasColumnName("last_ticket_id");

                            b1.Property<long?>("LogChannelId")
                                .HasColumnType("bigint")
                                .HasColumnName("log_channel_id");

                            b1.Property<long>("OpenedCategoryId")
                                .HasColumnType("bigint")
                                .HasColumnName("opened_category_id");

                            b1.Property<string>("OpenedNamePrefix")
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("opened_name_prefix");

                            b1.Property<string>("TicketCenterMessageDescription")
                                .HasColumnType("text")
                                .HasColumnName("ticket_center_message_description");

                            b1.Property<string>("TicketCenterMessageFields")
                                .HasColumnType("text")
                                .HasColumnName("ticket_center_message_fields");

                            b1.Property<string>("TicketWelcomeMessageDescription")
                                .HasColumnType("text")
                                .HasColumnName("ticket_welcome_message_description");

                            b1.Property<string>("TicketWelcomeMessageFields")
                                .HasColumnType("text")
                                .HasColumnName("ticket_welcome_message_fields");

                            b1.Property<DateTime?>("UpdatedAt")
                                .IsRequired()
                                .HasColumnType("timestamp")
                                .HasColumnName("updated_at");

                            b1.HasKey("GuildId");

                            b1.ToTable("guild_ticketing_config");

                            b1.WithOwner("Guild")
                                .HasForeignKey("GuildId");

                            b1.Navigation("Guild");
                        });

                    b.Navigation("ModerationConfig");

                    b.Navigation("TicketingConfig");
                });

            modelBuilder.Entity("Lisbeth.Bot.Domain.Entities.GuildServerBooster", b =>
                {
                    b.HasOne("Lisbeth.Bot.Domain.Entities.Guild", "Guild")
                        .WithMany("GuildServerBoosters")
                        .HasForeignKey("GuildId")
                        .HasPrincipalKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lisbeth.Bot.Domain.Entities.ServerBooster", "ServerBooster")
                        .WithMany("GuildServerBoosters")
                        .HasForeignKey("ServerBoosterId")
                        .HasPrincipalKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");

                    b.Navigation("ServerBooster");
                });

            modelBuilder.Entity("Lisbeth.Bot.Domain.Entities.Mute", b =>
                {
                    b.HasOne("Lisbeth.Bot.Domain.Entities.Guild", "Guild")
                        .WithMany("Mutes")
                        .HasForeignKey("GuildId")
                        .HasPrincipalKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Lisbeth.Bot.Domain.Entities.Prune", b =>
                {
                    b.HasOne("Lisbeth.Bot.Domain.Entities.Guild", "Guild")
                        .WithMany("Prunes")
                        .HasForeignKey("GuildId")
                        .HasPrincipalKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Lisbeth.Bot.Domain.Entities.RecurringReminder", b =>
                {
                    b.HasOne("Lisbeth.Bot.Domain.Entities.EmbedConfig", "EmbedConfig")
                        .WithOne("RecurringReminder")
                        .HasForeignKey("Lisbeth.Bot.Domain.Entities.RecurringReminder", "EmbedConfigId");

                    b.HasOne("Lisbeth.Bot.Domain.Entities.Guild", "Guild")
                        .WithMany("RecurringReminders")
                        .HasForeignKey("GuildId")
                        .HasPrincipalKey("GuildId");

                    b.Navigation("EmbedConfig");

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Lisbeth.Bot.Domain.Entities.Reminder", b =>
                {
                    b.HasOne("Lisbeth.Bot.Domain.Entities.EmbedConfig", "EmbedConfig")
                        .WithOne("Reminder")
                        .HasForeignKey("Lisbeth.Bot.Domain.Entities.Reminder", "EmbedConfigId");

                    b.HasOne("Lisbeth.Bot.Domain.Entities.Guild", "Guild")
                        .WithMany("Reminders")
                        .HasForeignKey("GuildId")
                        .HasPrincipalKey("GuildId");

                    b.Navigation("EmbedConfig");

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Lisbeth.Bot.Domain.Entities.RoleMenu", b =>
                {
                    b.HasOne("Lisbeth.Bot.Domain.Entities.EmbedConfig", "EmbedConfig")
                        .WithOne("RoleMenu")
                        .HasForeignKey("Lisbeth.Bot.Domain.Entities.RoleMenu", "EmbedConfigId");

                    b.HasOne("Lisbeth.Bot.Domain.Entities.Guild", "Guild")
                        .WithMany("RoleMenus")
                        .HasForeignKey("GuildId")
                        .HasPrincipalKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmbedConfig");

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Lisbeth.Bot.Domain.Entities.Tag", b =>
                {
                    b.HasOne("Lisbeth.Bot.Domain.Entities.EmbedConfig", "EmbedConfig")
                        .WithOne("Tag")
                        .HasForeignKey("Lisbeth.Bot.Domain.Entities.Tag", "EmbedConfigId");

                    b.HasOne("Lisbeth.Bot.Domain.Entities.Guild", "Guild")
                        .WithMany("Tags")
                        .HasForeignKey("GuildId")
                        .HasPrincipalKey("GuildId");

                    b.Navigation("EmbedConfig");

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Lisbeth.Bot.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("Lisbeth.Bot.Domain.Entities.Guild", "Guild")
                        .WithMany("Tickets")
                        .HasForeignKey("GuildId")
                        .HasPrincipalKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Lisbeth.Bot.Domain.Entities.EmbedConfig", b =>
                {
                    b.Navigation("RecurringReminder");

                    b.Navigation("Reminder");

                    b.Navigation("RoleMenu");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Lisbeth.Bot.Domain.Entities.Guild", b =>
                {
                    b.Navigation("Bans");

                    b.Navigation("GuildServerBoosters");

                    b.Navigation("Mutes");

                    b.Navigation("Prunes");

                    b.Navigation("RecurringReminders");

                    b.Navigation("Reminders");

                    b.Navigation("RoleMenus");

                    b.Navigation("Tags");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Lisbeth.Bot.Domain.Entities.ServerBooster", b =>
                {
                    b.Navigation("GuildServerBoosters");
                });
#pragma warning restore 612, 618
        }
    }
}
