// <auto-generated />

using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lisbeth.Bot.DataAccessLayer.Migrations
{
    [DbContext(typeof(LisbethBotDbContext))]
    [Migration("20220126112721_phishing")]
    partial class phishing
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lisbeth.Bot.Domain.Entities.Ban", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("AppliedById")
                        .HasColumnType("bigint")
                        .HasColumnName("applied_by_id");

                    b.Property<DateTime>("AppliedUntil")
                        .HasColumnType("timestamptz")
                        .HasColumnName("applied_until");

                    b.Property<DateTime?>("CreatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<long>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_disabled");

                    b.Property<long>("LiftedById")
                        .HasColumnType("bigint")
                        .HasColumnName("lifted_by_id");

                    b.Property<DateTime?>("LiftedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("lifted_on");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("reason");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserId"));

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.ToTable("ban", (string)null);
                });

            modelBuilder.Entity("Lisbeth.Bot.Domain.Entities.ChannelMessageFormat", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("ChannelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("channel_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ChannelId"));

                    b.Property<DateTime?>("CreatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("creator_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CreatorId"));

                    b.Property<long>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_disabled");

                    b.Property<long>("LastEditById")
                        .HasColumnType("bigint")
                        .HasColumnName("last_edit_by_id");

                    b.Property<string>("MessageFormat")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("message_format");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("GuildId");

                    b.ToTable("channel_message_format", (string)null);
                });

            modelBuilder.Entity("Lisbeth.Bot.Domain.Entities.EmbedConfig", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Author")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("author");

                    b.Property<string>("AuthorImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("author_image_url");

                    b.Property<string>("AuthorUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("author_url");

                    b.Property<DateTime?>("CreatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatorId")
                        .HasColumnType("bigint")
                        .HasColumnName("creator_id");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(4096)")
                        .HasColumnName("description");

                    b.Property<string>("Fields")
                        .HasColumnType("text")
                        .HasColumnName("fields");

                    b.Property<string>("Footer")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(2048)")
                        .HasColumnName("footer");

                    b.Property<string>("FooterImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("footer_image_url");

                    b.Property<string>("HexColor")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("hex_color");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_disabled");

                    b.Property<long>("LastEditById")
                        .HasColumnType("bigint")
                        .HasColumnName("last_edit_by_id");

                    b.Property<string>("Thumbnail")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("thumbnail");

                    b.Property<int?>("ThumbnailHeight")
                        .HasColumnType("integer")
                        .HasColumnName("thumbnail_height");

                    b.Property<int?>("ThumbnailWidth")
                        .HasColumnType("integer")
                        .HasColumnName("thumbnail_width");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("timestamptz")
                        .HasColumnName("Timestamp");

                    b.Property<string>("Title")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("embed_config", (string)null);
                });

            modelBuilder.Entity("Lisbeth.Bot.Domain.Entities.Guild", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("EmbedHexColor")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("embed_hex_color");

                    b.Property<long>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("GuildId"));

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_disabled");

                    b.Property<string>("PhishingDetection")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("phishing_detection");

                    b.Property<long?>("ReminderChannelId")
                        .HasColumnType("bigint")
                        .HasColumnName("reminder_channel_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("inviter_id");

                    b.HasKey("Id");

                    b.HasIndex("GuildId")
                        .IsUnique();

                    b.ToTable("guild", (string)null);
                });

            modelBuilder.Entity("Lisbeth.Bot.Domain.Entities.GuildServerBooster", b =>
                {
                    b.Property<long>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

                    b.Property<long>("ServerBoosterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

                    b.HasKey("GuildId", "ServerBoosterId");

                    b.HasIndex("ServerBoosterId");

                    b.ToTable("guild_server_booster", (string)null);
                });

            modelBuilder.Entity("Lisbeth.Bot.Domain.Entities.ModerationConfig", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("BaseMemberWelcomeMessage")
                        .HasColumnType("text")
                        .HasColumnName("member_welcome_message");

                    b.Property<DateTime?>("CreatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<long>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_disabled");

                    b.Property<long>("MemberEventsLogChannelId")
                        .HasColumnType("bigint")
                        .HasColumnName("member_events_log_channel_id");

                    b.Property<long?>("MemberWelcomeEmbedConfigId")
                        .HasColumnType("bigint")
                        .HasColumnName("member_welcome_embed_config_id");

                    b.Property<long>("MessageDeletedEventsLogChannelId")
                        .HasColumnType("bigint")
                        .HasColumnName("message_deleted_events_log_channel_id");

                    b.Property<long>("MessageUpdatedEventsLogChannelId")
                        .HasColumnType("bigint")
                        .HasColumnName("message_updated_events_log_channel_id");

                    b.Property<long>("ModerationLogChannelId")
                        .HasColumnType("bigint")
                        .HasColumnName("moderation_log_channel_id");

                    b.Property<long>("MuteRoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("mute_role_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("GuildId")
                        .IsUnique();

                    b.HasIndex("MemberWelcomeEmbedConfigId")
                        .IsUnique();

                    b.ToTable("moderation_config", (string)null);
                });

            modelBuilder.Entity("Lisbeth.Bot.Domain.Entities.Mute", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("AppliedById")
                        .HasColumnType("bigint")
                        .HasColumnName("applied_by_id");

                    b.Property<DateTime>("AppliedUntil")
                        .HasColumnType("timestamptz")
                        .HasColumnName("applied_until");

                    b.Property<DateTime?>("CreatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<long>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_disabled");

                    b.Property<long>("LiftedById")
                        .HasColumnType("bigint")
                        .HasColumnName("lifted_by_id");

                    b.Property<DateTime?>("LiftedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("lifted_on");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("reason");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserId"));

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.ToTable("mute", (string)null);
                });

            modelBuilder.Entity("Lisbeth.Bot.Domain.Entities.Prune", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint")
                        .HasColumnName("channel_id");

                    b.Property<int>("Count")
                        .HasColumnType("int")
                        .HasColumnName("count");

                    b.Property<DateTime?>("CreatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<long>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_disabled");

                    b.Property<string>("Messages")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("messages");

                    b.Property<long>("ModeratorId")
                        .HasColumnType("bigint")
                        .HasColumnName("moderator_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserId"));

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.ToTable("prune", (string)null);
                });

            modelBuilder.Entity("Lisbeth.Bot.Domain.Entities.Reminder", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<decimal?>("ChannelId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("channel_id");

                    b.Property<DateTime?>("CreatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatorId")
                        .HasColumnType("bigint")
                        .HasColumnName("creator_id");

                    b.Property<string>("CronExpression")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("cron_expression");

                    b.Property<long?>("EmbedConfigId")
                        .HasColumnType("bigint")
                        .HasColumnName("embed_config_id");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    b.Property<string>("HangfireId")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("hangfire_id");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_disabled");

                    b.Property<bool>("IsGuildReminder")
                        .HasColumnType("boolean")
                        .HasColumnName("is_guild_reminder");

                    b.Property<long>("LastEditById")
                        .HasColumnType("bigint")
                        .HasColumnName("lasted_edit_by_id");

                    b.Property<string>("Mentions")
                        .HasColumnType("text")
                        .HasColumnName("tags");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("SetFor")
                        .HasColumnType("timestamptz")
                        .HasColumnName("set_for");

                    b.Property<string>("Text")
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("EmbedConfigId")
                        .IsUnique();

                    b.HasIndex("GuildId");

                    b.ToTable("reminder", (string)null);
                });

            modelBuilder.Entity("Lisbeth.Bot.Domain.Entities.RoleMenu", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatorId")
                        .HasColumnType("bigint")
                        .HasColumnName("creator_id");

                    b.Property<string>("CustomButtonId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("custom_button_id");

                    b.Property<string>("CustomSelectComponentId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("custom_select_component_id");

                    b.Property<long?>("EmbedConfigId")
                        .HasColumnType("bigint")
                        .HasColumnName("embed_config_id");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_disabled");

                    b.Property<long>("LastEditById")
                        .HasColumnType("bigint")
                        .HasColumnName("lasted_edit_by_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Text")
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("EmbedConfigId")
                        .IsUnique();

                    b.HasIndex("GuildId");

                    b.ToTable("role_menu", (string)null);
                });

            modelBuilder.Entity("Lisbeth.Bot.Domain.Entities.RoleMenuOption", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomSelectOptionValueId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("custom_select_option_value_id");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("description");

                    b.Property<string>("Emoji")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("emoji");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_disabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.Property<long>("RoleMenuId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_menu_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("RoleMenuId");

                    b.ToTable("role_menu_option", (string)null);
                });

            modelBuilder.Entity("Lisbeth.Bot.Domain.Entities.ServerBooster", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<int>("BoostCount")
                        .HasColumnType("int")
                        .HasColumnName("boost_count");

                    b.Property<DateTime>("BoostingSince")
                        .HasColumnType("timestamptz")
                        .HasColumnName("boosting_since");

                    b.Property<DateTime?>("CreatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<long>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("GuildId"));

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_disabled");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserId"));

                    b.HasKey("Id");

                    b.ToTable("server_booster", (string)null);
                });

            modelBuilder.Entity("Lisbeth.Bot.Domain.Entities.Tag", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("AllowedRoleIds")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("allowed_role_ids");

                    b.Property<string>("AllowedUserIds")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("allowed_user_ids");

                    b.Property<DateTime?>("CreatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatorId")
                        .HasColumnType("bigint")
                        .HasColumnName("creator_id");

                    b.Property<long?>("EmbedConfigId")
                        .HasColumnType("bigint")
                        .HasColumnName("embed_config_id");

                    b.Property<long>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_disabled");

                    b.Property<long>("LastEditById")
                        .HasColumnType("bigint")
                        .HasColumnName("lasted_edit_by_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Text")
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("EmbedConfigId")
                        .IsUnique();

                    b.HasIndex("GuildId");

                    b.ToTable("tag", (string)null);
                });

            modelBuilder.Entity("Lisbeth.Bot.Domain.Entities.Ticket", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("AddedRoleIds")
                        .HasColumnType("text")
                        .HasColumnName("added_roles");

                    b.Property<string>("AddedUserIds")
                        .HasColumnType("text")
                        .HasColumnName("added_users");

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint")
                        .HasColumnName("channel_id");

                    b.Property<long?>("ClosedById")
                        .HasColumnType("bigint")
                        .HasColumnName("closed_by_id");

                    b.Property<DateTime?>("ClosedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("closed_on");

                    b.Property<DateTime?>("CreatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<long>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

                    b.Property<long>("GuildSpecificId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_specific_id");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_disabled");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean")
                        .HasColumnName("is_private");

                    b.Property<long?>("MessageCloseId")
                        .HasColumnType("bigint")
                        .HasColumnName("message_close_id");

                    b.Property<long>("MessageOpenId")
                        .HasColumnType("bigint")
                        .HasColumnName("message_open_id");

                    b.Property<long?>("MessageReopenId")
                        .HasColumnType("bigint")
                        .HasColumnName("message_reopen_id");

                    b.Property<long?>("ReopenedById")
                        .HasColumnType("bigint")
                        .HasColumnName("reopened_by_id");

                    b.Property<DateTime?>("ReopenedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("reopened_on");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserId"));

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.ToTable("ticket", (string)null);
                });

            modelBuilder.Entity("Lisbeth.Bot.Domain.Entities.TicketingConfig", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("BaseCenterMessage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("center_message_description");

                    b.Property<string>("BaseWelcomeMessage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("welcome_message_description");

                    b.Property<long?>("CenterEmbedConfigId")
                        .HasColumnType("bigint")
                        .HasColumnName("center_embed_config_id");

                    b.Property<double?>("CleanAfter")
                        .HasColumnType("bigint")
                        .HasColumnName("clean_after");

                    b.Property<double?>("CloseAfter")
                        .HasColumnType("bigint")
                        .HasColumnName("close_after");

                    b.Property<long>("ClosedCategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("closed_category_id");

                    b.Property<string>("ClosedNamePrefix")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("closed_name_prefix");

                    b.Property<DateTime?>("CreatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<long>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_disabled");

                    b.Property<long>("LastTicketId")
                        .HasColumnType("bigint")
                        .HasColumnName("last_ticket_id");

                    b.Property<long>("LogChannelId")
                        .HasColumnType("bigint")
                        .HasColumnName("log_channel_id");

                    b.Property<long>("OpenedCategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("opened_category_id");

                    b.Property<string>("OpenedNamePrefix")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("opened_name_prefix");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<long?>("WelcomeEmbedConfigId")
                        .HasColumnType("bigint")
                        .HasColumnName("welcome_embed_config_id");

                    b.HasKey("Id");

                    b.HasIndex("CenterEmbedConfigId")
                        .IsUnique();

                    b.HasIndex("GuildId")
                        .IsUnique();

                    b.HasIndex("WelcomeEmbedConfigId")
                        .IsUnique();

                    b.ToTable("ticketing_config", (string)null);
                });

            modelBuilder.Entity("MikyM.Common.Domain.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AffectedColumns")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("affected_columns");

                    b.Property<DateTime?>("CreatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_disabled");

                    b.Property<string>("NewValues")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("new_values");

                    b.Property<string>("OldValues")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("old_values");

                    b.Property<string>("PrimaryKey")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("primary_key");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("table_name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("Lisbeth.Bot.Domain.Entities.Ban", b =>
                {
                    b.HasOne("Lisbeth.Bot.Domain.Entities.Guild", "Guild")
                        .WithMany("Bans")
                        .HasForeignKey("GuildId")
                        .HasPrincipalKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Lisbeth.Bot.Domain.Entities.ChannelMessageFormat", b =>
                {
                    b.HasOne("Lisbeth.Bot.Domain.Entities.Guild", "Guild")
                        .WithMany("ChannelMessageFormats")
                        .HasForeignKey("GuildId")
                        .HasPrincipalKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Lisbeth.Bot.Domain.Entities.GuildServerBooster", b =>
                {
                    b.HasOne("Lisbeth.Bot.Domain.Entities.Guild", "Guild")
                        .WithMany("GuildServerBoosters")
                        .HasForeignKey("GuildId")
                        .HasPrincipalKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lisbeth.Bot.Domain.Entities.ServerBooster", "ServerBooster")
                        .WithMany("GuildServerBoosters")
                        .HasForeignKey("ServerBoosterId")
                        .HasPrincipalKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");

                    b.Navigation("ServerBooster");
                });

            modelBuilder.Entity("Lisbeth.Bot.Domain.Entities.ModerationConfig", b =>
                {
                    b.HasOne("Lisbeth.Bot.Domain.Entities.Guild", "Guild")
                        .WithOne("ModerationConfig")
                        .HasForeignKey("Lisbeth.Bot.Domain.Entities.ModerationConfig", "GuildId")
                        .HasPrincipalKey("Lisbeth.Bot.Domain.Entities.Guild", "GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lisbeth.Bot.Domain.Entities.EmbedConfig", "MemberWelcomeEmbedConfig")
                        .WithOne("ModerationConfig")
                        .HasForeignKey("Lisbeth.Bot.Domain.Entities.ModerationConfig", "MemberWelcomeEmbedConfigId");

                    b.Navigation("Guild");

                    b.Navigation("MemberWelcomeEmbedConfig");
                });

            modelBuilder.Entity("Lisbeth.Bot.Domain.Entities.Mute", b =>
                {
                    b.HasOne("Lisbeth.Bot.Domain.Entities.Guild", "Guild")
                        .WithMany("Mutes")
                        .HasForeignKey("GuildId")
                        .HasPrincipalKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Lisbeth.Bot.Domain.Entities.Prune", b =>
                {
                    b.HasOne("Lisbeth.Bot.Domain.Entities.Guild", "Guild")
                        .WithMany("Prunes")
                        .HasForeignKey("GuildId")
                        .HasPrincipalKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Lisbeth.Bot.Domain.Entities.Reminder", b =>
                {
                    b.HasOne("Lisbeth.Bot.Domain.Entities.EmbedConfig", "EmbedConfig")
                        .WithOne("Reminder")
                        .HasForeignKey("Lisbeth.Bot.Domain.Entities.Reminder", "EmbedConfigId");

                    b.HasOne("Lisbeth.Bot.Domain.Entities.Guild", "Guild")
                        .WithMany("Reminders")
                        .HasForeignKey("GuildId")
                        .HasPrincipalKey("GuildId");

                    b.Navigation("EmbedConfig");

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Lisbeth.Bot.Domain.Entities.RoleMenu", b =>
                {
                    b.HasOne("Lisbeth.Bot.Domain.Entities.EmbedConfig", "EmbedConfig")
                        .WithOne("RoleMenu")
                        .HasForeignKey("Lisbeth.Bot.Domain.Entities.RoleMenu", "EmbedConfigId");

                    b.HasOne("Lisbeth.Bot.Domain.Entities.Guild", "Guild")
                        .WithMany("RoleMenus")
                        .HasForeignKey("GuildId")
                        .HasPrincipalKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmbedConfig");

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Lisbeth.Bot.Domain.Entities.RoleMenuOption", b =>
                {
                    b.HasOne("Lisbeth.Bot.Domain.Entities.RoleMenu", "RoleMenu")
                        .WithMany("RoleMenuOptions")
                        .HasForeignKey("RoleMenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoleMenu");
                });

            modelBuilder.Entity("Lisbeth.Bot.Domain.Entities.Tag", b =>
                {
                    b.HasOne("Lisbeth.Bot.Domain.Entities.EmbedConfig", "EmbedConfig")
                        .WithOne("Tag")
                        .HasForeignKey("Lisbeth.Bot.Domain.Entities.Tag", "EmbedConfigId");

                    b.HasOne("Lisbeth.Bot.Domain.Entities.Guild", "Guild")
                        .WithMany("Tags")
                        .HasForeignKey("GuildId")
                        .HasPrincipalKey("GuildId");

                    b.Navigation("EmbedConfig");

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Lisbeth.Bot.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("Lisbeth.Bot.Domain.Entities.Guild", "Guild")
                        .WithMany("Tickets")
                        .HasForeignKey("GuildId")
                        .HasPrincipalKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Lisbeth.Bot.Domain.Entities.TicketingConfig", b =>
                {
                    b.HasOne("Lisbeth.Bot.Domain.Entities.EmbedConfig", "CenterEmbedConfig")
                        .WithOne("TicketingConfigWithCenterMessage")
                        .HasForeignKey("Lisbeth.Bot.Domain.Entities.TicketingConfig", "CenterEmbedConfigId");

                    b.HasOne("Lisbeth.Bot.Domain.Entities.Guild", "Guild")
                        .WithOne("TicketingConfig")
                        .HasForeignKey("Lisbeth.Bot.Domain.Entities.TicketingConfig", "GuildId")
                        .HasPrincipalKey("Lisbeth.Bot.Domain.Entities.Guild", "GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lisbeth.Bot.Domain.Entities.EmbedConfig", "WelcomeEmbedConfig")
                        .WithOne("TicketingConfigWithWelcomeMessage")
                        .HasForeignKey("Lisbeth.Bot.Domain.Entities.TicketingConfig", "WelcomeEmbedConfigId");

                    b.Navigation("CenterEmbedConfig");

                    b.Navigation("Guild");

                    b.Navigation("WelcomeEmbedConfig");
                });

            modelBuilder.Entity("Lisbeth.Bot.Domain.Entities.EmbedConfig", b =>
                {
                    b.Navigation("ModerationConfig");

                    b.Navigation("Reminder");

                    b.Navigation("RoleMenu");

                    b.Navigation("Tag");

                    b.Navigation("TicketingConfigWithCenterMessage");

                    b.Navigation("TicketingConfigWithWelcomeMessage");
                });

            modelBuilder.Entity("Lisbeth.Bot.Domain.Entities.Guild", b =>
                {
                    b.Navigation("Bans");

                    b.Navigation("ChannelMessageFormats");

                    b.Navigation("GuildServerBoosters");

                    b.Navigation("ModerationConfig");

                    b.Navigation("Mutes");

                    b.Navigation("Prunes");

                    b.Navigation("Reminders");

                    b.Navigation("RoleMenus");

                    b.Navigation("Tags");

                    b.Navigation("TicketingConfig");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Lisbeth.Bot.Domain.Entities.RoleMenu", b =>
                {
                    b.Navigation("RoleMenuOptions");
                });

            modelBuilder.Entity("Lisbeth.Bot.Domain.Entities.ServerBooster", b =>
                {
                    b.Navigation("GuildServerBoosters");
                });
#pragma warning restore 612, 618
        }
    }
}
